services:
   dragonfly:
      image: docker.dragonflydb.io/dragonflydb/dragonfly
      restart: always
      env_file: .env
      ports:
         - "${DRAGONFLY_PORT}:6379"
      expose:
         - "${DRAGONFLY_PORT}"
      # command: [""]
      volumes:
         - dragonfly-data:/data

   postgres:
      image: postgres:17-alpine
      restart: always
      env_file: .env
      environment:
         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
         POSTGRES_USER: ${POSTGRES_USER}
         POSTGRES_DB: ${POSTGRES_DB}
         PGDATA: ${POSTGRES_DATA}
      ports:
         - "${POSTGRES_PORT}:5432"
      expose:
         - "${POSTGRES_PORT}"
      volumes:
         - postgres-data:${POSTGRES_DATA}

   nats:
      image: nats:2.9-alpine
      restart: always
      ports:
         - "${NATS_PORT}:4222"
         - "${NATS_HTTP_PORT}:8222"
      expose:
         - "${NATS_PORT}"
         - "${NATS_HTTP_PORT}"
      command: [
         "--jetstream",
         "--store_dir=/data",
         "--server_name=nats-server"
      ]
      volumes:
         - nats-data:/data
      env_file: .env
      environment:
         - NATS_USERNAME=${NATS_USERNAME:-}
         - NATS_PASSWORD=${NATS_PASSWORD:-}

volumes:
   dragonfly-data:
   postgres-data:
